FROM node:12.18.3

ENV NODE_ENV=development
ENV NODE_PORT=3000

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package*.json ./
COPY tsconfig.json ./

RUN npm install
COPY ./src ./src
RUN npm run build

FROM node:12.18.3

ENV NODE_ENV="development"
ENV NODE_PORT=3000

WORKDIR /usr/src/app

COPY package*.json ./
COPY tsconfig.json ./
COPY nodemon.json ./
RUN npm install
COPY --from=0 /usr/src/app/dist ./dist
COPY --from=0 /usr/src/app/src ./src

EXPOSE 3000
CMD npm run start:dev
